### ISSUE TITLE
5xx Errors Reported from Google

### ISSUE THREAD

**Issue by kmorton1988** [tbm0115/PokemonUtilities#22]
pages at: 
/pokemon/aegislash
/pokemon/darmanitan
/pokemon/meowstic
/pokemon/unown

producing errors/printout of code. 

![chrome_2018-11-02_15-53-42](https://user-images.githubusercontent.com/11138976/47944241-8bc31700-deb7-11e8-9d1b-c3354fe04bb9.png)

**Comment by tbm0115** [comment]
Should be fixed, but I'm waiting for Google to crawl the pages to verify.

**Comment by tbm0115** [comment]
Fixed the 5xx errors, but the issue may persist with other aspects of the site. Consider adding a specific 404 redirect for these types of resources, perhaps something without a layout.
